void*	emalloc(ulong);
void*	erealloc(void*, ulong);
void	grab(int);
void	toss(void);
void	flush(void);
char*	demof(char*);
u16int*	readmap(int);
void	dat(char*);
void	fizz(void);
void	fizzop(int, int);
void	fadeout(void);
void	fadein(void);
void	fadeop(Col*, int);
void	palpic(uchar*);
void	out(void);
void	pput(int, int, int, int, uchar*);
void	put(int, int, int, int, int);
int	txt(int, int, char*, int);
int	txtnl(int, int, char*, int);
int	txth(char*);
int	txtw(char*);
void	fill(int);
void	pic(int, int, int);
void	pictxt(int, int, char*);
void	hudf(void);
void	hudh(void);
void	hudl(void);
void	hudm(void);
void	huda(void);
void	hudk(void);
void	hudw(void);
void	hudp(void);
void	clear(void);
void	scalspr(int, int, int);
s32int	ffs(s32int, s32int);
void	render(void);
void	initscal(void);
void	setvw(int);
void	tab(void);
void	gend(void);
void	mstep(void);
void	init(char*);
void	drop(Tile*, int);
void	dropen(Door*);
void	druse(Door*);
void	osetglobal(Obj*);
void	ostate(Obj*, State*);
Obj*	onew(void);
Obj*	ospawn(Tile*, State*);
void	uworld(void);
void	mapmus(void);
void	initmap(void);
void	sodmap(void);
void	camwarp(void);
void	bonus(Static*);
int	rnd(void);
void	gstep(void);
void	demo(void);
void	initg(int, uchar*);
uchar*	opl2out(uchar*, int);
void	opl2wr(int, int);
void	opl2init(int);
void	sndstep(void);
void	stopsfx(void);
int	lastsfx(void);
void	sfxatt(int, int, int, int);
void	sfx(int);
void	stopmus(void);
void	mus(int);
void	initsnd(void);
