void*	emalloc(ulong);
void*	erealloc(void *, ulong);
void	flush(void);
void	dat(char *);
void	palpic(uchar *);
void	fadeout(int);
void	fadein(int);
void	out(void);
void	put(int, int, int, int, uchar *, int);
int	txt(int, int, char *, int);
int	txtnl(int, int, char *, int);
int	txtw(char *s);
void	fill(int);
void	pic(int, int, int);
void	demos(void);
void	init(void);
int	rnd(void);
void	vbl(int);
void	delay(int);
void	initg(int);
void	stopmus(void);
void	playmus(int);
